name: Ruff Formatting & Linting

on: [push, pull_request]

jobs:
    ruff:
      name: Run Ruff Commands
      runs-on: ubuntu-latest
  
      steps:
        # Checkout the repository
        - name: Checkout Repository
          uses: actions/checkout@v2
        
        # Set up Python environment
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12.0'

        # Install Ruff
        - name: Install Ruff
          run: pip install ruff

        # Runf Ruff
        - name: Run Ruff Fix
          run: ruff --fix . --ignore=F841,E712 --line-length=120
  
        - name: Run Ruff Format
          run: ruff format .
        
        # Commit changes if any
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Ruff linting/formatting by GitHub Actions"
