name: Test with Redis and Pytest

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --python 3.12.0

      # Wait for Redis to be ready -> TODO: integrate when needed
      # - name: Check Redis is running
      #   run: |
      #     sleep 5
      #     redis-cli ping

      # Run pytest with Redis
      - name: Run tests with pytest
        env:
          REDIS_URL: redis://localhost:6379/0
        run: pytest --maxfail=1 --disable-warnings -q

      # Optionally: Store test results
      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: pytest-results
      #     path: pytest-results.xml
